Everything in pytorch is based on Tensor operations. A tensor can have different dimensions, so it can be 1d, 2d, or even 3d and higher

In [2]:
import torch

## 1. Creating a Tensor

torch.empty(size) creates a tensor of given size.

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


torch.rand(size) creates a tensor of given size with random numbers between [0, 1]  

randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, while `rand` generates numbers from a uniform distribution between 0 and 1

In [4]:
x = torch.rand(2, 3, 3)
print(x)
x = torch.randn(2, 3, 3)
print(x)

tensor([[[0.4914, 0.7226, 0.6093],
         [0.8039, 0.1827, 0.9185],
         [0.7343, 0.3950, 0.4696]],

        [[0.9430, 0.1709, 0.3336],
         [0.1067, 0.2452, 0.6319],
         [0.1224, 0.0176, 0.4045]]])
tensor([[[ 0.4042,  2.0644, -0.6347],
         [-0.4724, -0.8734,  0.7356],
         [-0.4951, -0.8558, -0.2297]],

        [[-0.2834,  0.8381, -0.7173],
         [ 0.3064, -0.2263, -0.3621],
         [ 0.9541, -0.1379,  0.3192]]])


torch.ones() or torch.zeros() create tensors containing all zeros or ones.

In [4]:
x = torch.ones(2, 3, 3)
print(x)
x = torch.zeros(2, 3, 3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


specify type of values contained in a tensor using dtype=torch.int. float32 is the default

In [5]:
x = torch.empty(4, 3, dtype=torch.int)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)



x = torch.empty(4, 3, dtype=torch.float16)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.Size([4, 3])
torch.int32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.Size([4, 3])
torch.float16


## 2. requires_grad argument

This will tell pytorch that it will need to calculate the gradients for this tensor later in your optimization steps  
i.e. this is a variable in your model that you want to optimize

In [6]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

x = torch.tensor([5.5, 3], requires_grad=True)

torch.Size([2])


## 3. Addition, Substraction, Multiplication

### Addition

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.add(x,y) 
print(z)

y.add_(x)   #In place addition operation
print(y)

tensor([[0.8744, 0.4369],
        [0.7998, 0.5214]])
tensor([[0.4430, 0.0133],
        [0.2547, 0.7677]])
tensor([[1.3174, 0.4502],
        [1.0545, 1.2891]])
tensor([[1.3174, 0.4502],
        [1.0545, 1.2891]])


### Substraction

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.subtract(x,y) 
print(z)

y.subtract_(x)   #In place addition operation
print(y)

tensor([[0.3152, 0.3095],
        [0.9714, 0.0377]])
tensor([[0.4810, 0.8729],
        [0.6769, 0.1362]])
tensor([[-0.1658, -0.5634],
        [ 0.2945, -0.0985]])
tensor([[ 0.1658,  0.5634],
        [-0.2945,  0.0985]])


### Multiply

In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.multiply(x,y) 
print(z)

y.multiply_(x)   #In place addition operation
print(y)

tensor([[0.1793, 0.2177],
        [0.0040, 0.9615]])
tensor([[0.0665, 0.9014],
        [0.9907, 0.8887]])
tensor([[0.0119, 0.1963],
        [0.0040, 0.8545]])
tensor([[0.0119, 0.1963],
        [0.0040, 0.8545]])


## 4. Slicing Operation on Tensors

In [10]:
x = torch.rand(5,3)
print(x)

print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.5960, 0.0988, 0.7125],
        [0.9343, 0.2322, 0.4439],
        [0.9782, 0.2972, 0.2267],
        [0.7900, 0.1999, 0.7970],
        [0.9261, 0.5843, 0.2100]])
tensor([0.5960, 0.9343, 0.9782, 0.7900, 0.9261])
tensor([0.9343, 0.2322, 0.4439])
tensor(0.2322)


Get the actual value if only 1 element in your tensor using *.item()* command.

In [11]:
print(x[1,1].item())

0.2322278618812561


## 5. Reshaping PyTorch Tensors

torch.view() can be used for reshaping.

In [12]:
x = torch.rand(4,4)
print(x)
y = x.view(8,2)
print(y.size())
y = x.view(16)
print(y.size())

tensor([[0.3601, 0.9631, 0.5724, 0.2088],
        [0.2896, 0.0957, 0.5264, 0.4370],
        [0.0451, 0.6615, 0.2996, 0.9000],
        [0.5281, 0.3114, 0.9373, 0.1948]])
torch.Size([8, 2])
torch.Size([16])


In [13]:
y = x.view(-1,8)    #if -1 pytorch will automatically determine the necessary size
print(y.size())

torch.Size([2, 8])


## 6. Torch Tensor to Numpy Array

b = a.numpy() will convert torch tensor a, to numpy array b

In [14]:
import numpy as np

a = torch.ones(5)
print(type(a))
print(a)

b = a.numpy()

print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


Carful: If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other

In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


b = torch.from_numpy(a) converts a numpy array a, to torch tensor b.

In [16]:
a = np.ones(5)
print(a)
print(type(a))

b = torch.from_numpy(a)

print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


Carful: If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other

In [17]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 7. Sending a Torch Tensor to GPU and Moving a Tensor back to CPU

Works only for Nvidea GPUs

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")

    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #z.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")


Converted to Apple Metal Performance Shredder

In [19]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    
    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")

tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([2., 2., 2., 2., 2.], device='mps:0')


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

This error will arise if you try to convert an "mps" tensor to numpy.