# 01. Tensor Basics

Everything in pytorch is based on Tensor operations. A tensor can have different dimensions, so it can be 1d, 2d, or even 3d and higher

In [1]:
import torch

## 1. Creating a Tensor

torch.empty(size) creates a tensor of given size.

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


torch.rand(size) creates a tensor of given size with random numbers between [0, 1]  

randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, while `rand` generates numbers from a uniform distribution between 0 and 1

In [3]:
x = torch.rand(2, 3, 3)
print(x)
x = torch.randn(2, 3, 3)
print(x)

tensor([[[0.9137, 0.4864, 0.8796],
         [0.0041, 0.3042, 0.8897],
         [0.4881, 0.6847, 0.1004]],

        [[0.1655, 0.7399, 0.3011],
         [0.4482, 0.7912, 0.6165],
         [0.3272, 0.4475, 0.8606]]])
tensor([[[ 0.6747,  0.3349, -1.2207],
         [ 0.3844, -0.4874,  1.1519],
         [-1.0025, -0.2822,  0.3198]],

        [[-1.5490, -1.5982,  0.3617],
         [ 0.9405, -0.3373, -0.8545],
         [-1.7060, -0.4762, -0.6453]]])


torch.ones() or torch.zeros() create tensors containing all zeros or ones.

In [4]:
x = torch.ones(2, 3, 3)
print(x)
x = torch.zeros(2, 3, 3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


specify type of values contained in a tensor using dtype=torch.int. float32 is the default

In [5]:
x = torch.empty(4, 3, dtype=torch.int)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)



x = torch.empty(4, 3, dtype=torch.float16)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.Size([4, 3])
torch.int32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.Size([4, 3])
torch.float16


## 2. requires_grad argument

This will tell pytorch that it will need to calculate the gradients for this tensor later in your optimization steps  
i.e. this is a variable in your model that you want to optimize

In [6]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

x = torch.tensor([5.5, 3], requires_grad=True)

torch.Size([2])


## 3. Addition, Substraction, Multiplication

### Addition

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.add(x,y) 
print(z)

y.add_(x)   #In place addition operation
print(y)

tensor([[0.7381, 0.7646],
        [0.7257, 0.2384]])
tensor([[0.0997, 0.3840],
        [0.2101, 0.1754]])
tensor([[0.8378, 1.1487],
        [0.9358, 0.4138]])
tensor([[0.8378, 1.1487],
        [0.9358, 0.4138]])


### Substraction

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.subtract(x,y) 
print(z)

y.subtract_(x)   #In place addition operation
print(y)

tensor([[0.2096, 0.9651],
        [0.2702, 0.7696]])
tensor([[0.3535, 0.0347],
        [0.9646, 0.6480]])
tensor([[-0.1439,  0.9304],
        [-0.6944,  0.1216]])
tensor([[ 0.1439, -0.9304],
        [ 0.6944, -0.1216]])


### Multiply

In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print (x)
print (y)

#z = x + y 
z = torch.multiply(x,y) 
print(z)

y.multiply_(x)   #In place addition operation
print(y)

tensor([[0.4631, 0.0701],
        [0.4348, 0.6621]])
tensor([[0.2257, 0.4617],
        [0.6243, 0.6705]])
tensor([[0.1045, 0.0324],
        [0.2714, 0.4440]])
tensor([[0.1045, 0.0324],
        [0.2714, 0.4440]])


## 4. Slicing Operation on Tensors

In [10]:
x = torch.rand(5,3)
print(x)

print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.9651, 0.2648, 0.0263],
        [0.8813, 0.5249, 0.1373],
        [0.0572, 0.4364, 0.0129],
        [0.8746, 0.6976, 0.2975],
        [0.8179, 0.2767, 0.1420]])
tensor([0.9651, 0.8813, 0.0572, 0.8746, 0.8179])
tensor([0.8813, 0.5249, 0.1373])
tensor(0.5249)


Get the actual value if only 1 element in your tensor using *.item()* command.

In [11]:
print(x[1,1].item())

0.5249464511871338


## 5. Reshaping PyTorch Tensors

torch.view() can be used for reshaping.

In [12]:
x = torch.rand(4,4)
print(x)
y = x.view(8,2)
print(y.size())
y = x.view(16)
print(y.size())

tensor([[0.1426, 0.5695, 0.4975, 0.0301],
        [0.0598, 0.4400, 0.4016, 0.3954],
        [0.4191, 0.5990, 0.5349, 0.3023],
        [0.9416, 0.2607, 0.2962, 0.6273]])
torch.Size([8, 2])
torch.Size([16])


In [13]:
y = x.view(-1,8)    #if -1 pytorch will automatically determine the necessary size
print(y.size())

torch.Size([2, 8])


## 6. Torch Tensor to Numpy Array

b = a.numpy() will convert torch tensor a, to numpy array b

In [14]:
import numpy as np

a = torch.ones(5)
print(type(a))
print(a)

b = a.numpy()

print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


Carful: If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other

In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


b = torch.from_numpy(a) converts a numpy array a, to torch tensor b.

In [24]:
a = np.ones(5)
print(a)
print(type(a))

b = torch.from_numpy(a)
c = torch.from_numpy(a.astype(np.float16))

print(b)
print(type(b))
print(c)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float16)


Carful: If the Tensor is on the CPU (not the GPU), both objects will share the same memory location, so changing one will also change the other

In [17]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 7. Sending a Torch Tensor to GPU and Moving a Tensor back to CPU

Works only for Nvidea GPUs

In [18]:
if torch.cuda.is_available():
    device = torch.device("cuda")

    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #z.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")


Converted to Apple Metal Performance Shredder

In [19]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    
    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")

tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([2., 2., 2., 2., 2.], device='mps:0')


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

This error will arise if you try to convert an "mps" tensor to numpy.