In [90]:
import torch

In [91]:
x = torch.empty(2, 3, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [92]:
x = torch.rand(2, 3, 3)
print(x)

tensor([[[0.2794, 0.1432, 0.8981],
         [0.1936, 0.2628, 0.7361],
         [0.1670, 0.5856, 0.1542]],

        [[0.3610, 0.0782, 0.9989],
         [0.8797, 0.3575, 0.5151],
         [0.0964, 0.8094, 0.3173]]])


In [93]:
x = torch.ones(2, 3, 3)
print(x)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [94]:
x = torch.zeros(2, 3, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [95]:
x = torch.empty(2, 3, 3, dtype=torch.int)
print(x)

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)


In [96]:
x = torch.empty(2, 3, 3, dtype=torch.float16)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float16)


In [97]:
import torch
x = torch. rand (2,2)
y = torch. rand (2,2)
print (x)
print (y)

#z = x + y 
z = torch.add(x,y) 
# w = x-y
w = torch.sub(x,y)
v = x*y

print(v)
print(w)
print(z)

tensor([[0.9889, 0.6158],
        [0.5699, 0.1972]])
tensor([[0.0543, 0.0201],
        [0.6193, 0.3777]])
tensor([[0.0537, 0.0124],
        [0.3530, 0.0745]])
tensor([[ 0.9347,  0.5957],
        [-0.0494, -0.1805]])
tensor([[1.0432, 0.6359],
        [1.1893, 0.5749]])


In [98]:
y.multiply_(x)

tensor([[0.0537, 0.0124],
        [0.3530, 0.0745]])

In [99]:
y.add_(x)

tensor([[1.0426, 0.6282],
        [0.9229, 0.2717]])

In [100]:
print(torch.multiply(x,y))

tensor([[1.0311, 0.3868],
        [0.5260, 0.0536]])


In [101]:
x = torch.rand(5,3)
print(x)

tensor([[0.4599, 0.2260, 0.9732],
        [0.7438, 0.1627, 0.5062],
        [0.6226, 0.3522, 0.3826],
        [0.1716, 0.3652, 0.0201],
        [0.7665, 0.8484, 0.2304]])


In [102]:
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item()) 

tensor([0.4599, 0.7438, 0.6226, 0.1716, 0.7665])
tensor([0.7438, 0.1627, 0.5062])
0.16271448135375977


In [103]:
x = torch.rand(4,4)
print(x)
y = x.view(8,2)
print(y)

tensor([[0.0744, 0.2060, 0.6489, 0.0111],
        [0.5858, 0.2178, 0.6520, 0.1021],
        [0.5471, 0.8060, 0.6918, 0.0337],
        [0.1045, 0.0017, 0.3356, 0.2375]])
tensor([[0.0744, 0.2060],
        [0.6489, 0.0111],
        [0.5858, 0.2178],
        [0.6520, 0.1021],
        [0.5471, 0.8060],
        [0.6918, 0.0337],
        [0.1045, 0.0017],
        [0.3356, 0.2375]])


In [104]:
y = x.view(16)
print(y)
print(y.size())

tensor([0.0744, 0.2060, 0.6489, 0.0111, 0.5858, 0.2178, 0.6520, 0.1021, 0.5471,
        0.8060, 0.6918, 0.0337, 0.1045, 0.0017, 0.3356, 0.2375])
torch.Size([16])


In [105]:
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.0744, 0.2060, 0.6489, 0.0111, 0.5858, 0.2178, 0.6520, 0.1021],
        [0.5471, 0.8060, 0.6918, 0.0337, 0.1045, 0.0017, 0.3356, 0.2375]])
torch.Size([2, 8])


In [106]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))


tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [107]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [109]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [110]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [113]:
torch.cuda.is_available()

False

In [125]:
if torch.cuda.is_available():
    device = torch.device("cuda")

    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #z.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")


In [124]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    
    x = torch.ones(5, device=device)    #Creating a tensor on GPU
    print(x)
    y = torch.ones_like(x)  #This creates a tensor of shape like x.
    y = y.to(device)        #Creating a tensor and moving to GPU later.
    print(y)
    z = x + y   #Will be performed on GPU
    print(z)
    #z.numpy() #Should give an error since numpy cannot handle GPU sensors.
    z = z.to("cpu")

tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([1., 1., 1., 1., 1.], device='mps:0')
tensor([2., 2., 2., 2., 2.], device='mps:0')
